on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:

name: Rust Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:  
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: "thumbv6m-none-eabi"
          components: "clippy,rustfmt"
      - name:
        working-directory: "firmware"
        run: cargo check --all-targets
      - name:
        working-directory: "lib/pnpfeeder"
        run: cargo check --all-targets

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:  
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: "thumbv6m-none-eabi"
          components: "clippy,rustfmt"
      - name:
        working-directory: "lib/pnpfeeder"
        run: cargo test


  build:
    name: Build and upload firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:  
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: "thumbv6m-none-eabi"
          components: "clippy,rustfmt"
      - name: install libudev
        run: sudo apt-get install -y libudev-dev
      - 
        working-directory: "firmware"
        run: cargo install --locked --no-default-features elf2uf2-rs
      -
        working-directory: "firmware"
        run: cargo build --release
      -
        working-directory: "firmware"
        run: elf2uf2-rs target/thumbv6m-none-eabi/release/pico target/thumbv6m-none-eabi/release/pico.uf2
      - uses: actions/upload-artifact@v3
        with:
          name: rp2040-0816-pico.uf2
          path: firmware/target/thumbv6m-none-eabi/release/pico.uf2

  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:  
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: "thumbv6m-none-eabi"
          components: "clippy,rustfmt"
      - 
        working-directory: "firmware"
        run: cargo fmt --all -- --check
      - 
        working-directory: "lib/pnpfeeder"
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:  
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: "thumbv6m-none-eabi"
          components: "clippy,rustfmt"
      - 
        working-directory: "firmware"
        run: cargo clippy --all-targets -- -D warnings
      - 
        working-directory: "lib/pnpfeeder"
        run: cargo clippy --all-targets -- -D warnings