on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:

name: Rust Continuous integration

jobs:
  test:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:  
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: "thumbv6m-none-eabi"
          components: "clippy,rustfmt"
      - name: check
        working-directory: "firmware"
        run: cargo check

  build:
    name: Build and upload firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:  
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: "thumbv6m-none-eabi"
          components: "clippy,rustfmt"
      - name: Install libudev
        run: sudo apt-get install -y libudev-dev
      - 
        working-directory: "firmware"
        run: cargo install --locked --no-default-features elf2uf2-rs
      -
        working-directory: "firmware"
        run: cargo build --release
      -
        working-directory: "firmware"
        run: elf2uf2-rs target/thumbv6m-none-eabi/release/rp2040-0816 target/thumbv6m-none-eabi/release/rp2040-0816.uf2
      - uses: actions/upload-artifact@v3
        with:
          name: rp2040-0816.uf2
          path: firmware/target/thumbv6m-none-eabi/release/rp2040-0816.uf2

  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:  
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: "thumbv6m-none-eabi"
          components: "clippy,rustfmt"
      - 
        working-directory: "firmware"
        run: cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:  
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: "thumbv6m-none-eabi"
          components: "clippy,rustfmt"
      - 
        working-directory: "firmware"
        run: cargo clippy -- -D warnings